# Generated by Django 2.1.7 on 2019-04-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('desk', '0001_initial'),
        ('api_rules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrow',
            name='related_desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Desk'),
        ),
    ]
