# Generated by Django 2.1.7 on 2019-03-25 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
        ('desk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='current_executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.CustomUser'),
        ),
        migrations.AddField(
            model_name='task',
            name='related_column',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Column'),
        ),
        migrations.AddField(
            model_name='desk',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.CustomUser'),
        ),
        migrations.AddField(
            model_name='column',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_auth.CustomUser'),
        ),
        migrations.AddField(
            model_name='column',
            name='related_desk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desk.Desk'),
        ),
    ]
