# Generated by Django 2.1.7 on 2019-04-13 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20190405_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('High', 'HIGH'), ('Medium', 'MEDIUM'), ('Low', 'LOW')], default='Середній', max_length=8),
        ),
    ]
