# Generated by Django 2.1.7 on 2019-04-01 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20190401_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='current_executor',
            field=models.ForeignKey(help_text='ID of user for who task is assigned', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateField(blank=True, help_text='Deadline of the task. format=Date(MM-DD-YYYY)'),
        ),
    ]
