# Generated by Django 2.1.7 on 2019-04-01 09:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0003_auto_20190401_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_deadline',
            field=models.DateField(default=django.utils.timezone.now, help_text='Deadline of the task. format=Date(MM-DD-YYYY)'),
        ),
    ]
