# Generated by Django 2.1.7 on 2019-04-01 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_auto_20190401_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='related_task',
            field=models.ForeignKey(help_text='ID of task for which this one is related', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='desk.Task'),
        ),
    ]
