# Generated by Django 2.1.7 on 2019-04-03 08:00

import desk.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0005_auto_20190403_0653'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=desk.model.upload_comment_image),
        ),
    ]
