# Generated by Django 2.1.7 on 2019-04-03 09:58

import desk.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0006_comment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=desk.model.upload_task_image),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(default='Середній', max_length=8),
        ),
    ]
